remote_theme: coursweb/jk-theme
title: Cours Bricks
description: Module de cours sur Bricks et WordPress.
lang: fr-FR
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Bricks
   url: https://cours-web.ch/bricks/


   # Footer content
# Content is split in three columns.   
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2026</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/bricks">Lien Github</a></li></ul>